"""Simulate text_encoder_initial_device() before and after the fix.

Models the decision logic across vendors, VRAM sizes, RAM sizes,
model sizes, workloads and inference resolutions.
"""
from __future__ import annotations

# ── vendor definitions ──────────────────────────────────────────────
# Each vendor defines how get_free_memory() behaves for its GPU device.

VENDORS: list[dict] = [
    {
        "name": "NVIDIA CUDA",
        "abbr": "CUDA",
        "free_vram_fn": lambda total, used, inf: total - used - inf,
    },
    {
        "name": "Intel XPU",
        "abbr": "XPU",
        "free_vram_fn": lambda total, used, inf: total - used - inf,
    },
    {
        "name": "AMD DirectML",
        "abbr": "DML",
        # Hardcoded 1 GB in ComfyUI get_free_memory() — see line 1663
        "free_vram_fn": lambda _total, _used, _inf: 1.0,
    },
    {
        "name": "Apple MPS",
        "abbr": "MPS",
        # MPS uses system RAM.  is_device_mps() returns True so the
        # function returns load_device early — this column is for
        # completeness only.
        "free_vram_fn": lambda total, _used, _inf: total,  # not actually reached
    },
    {
        "name": "Ascend NPU",
        "abbr": "NPU",
        "free_vram_fn": lambda total, used, inf: total - used - inf,
    },
    {
        "name": "Cambricon MLU",
        "abbr": "MLU",
        "free_vram_fn": lambda total, used, inf: total - used - inf,
    },
]

# ── hardware dimensions ─────────────────────────────────────────────

VRAMS_GB = [4, 6, 8, 12, 16, 20, 24, 32, 48]
RAMS_GB  = [8, 16, 32, 64, 96, 128, 256]

# size in GiB generated by parameters * dtype_size
MODELS = [
    ("SD1.5 CLIP fp32",    1.3),
    ("SDXL CLIP",          2.0),
    ("Qwen3-4B fp16",      7.6),   # user
    ("Flux TEs",           8.5),
    ("Llama-8B fp16",     15.0),
    ("Qwen3-4B fp32",     15.2),
]

# (label, vram_used_before_te_gb, inference_overhead_gb)
SCENARIOS: list[tuple[str, float, float]] = [
    ("clean, 512x512",   0.5, 0.5),
    ("clean, 1024x1024", 0.5, 2.0),
    ("clean, 2048x2048", 0.5, 8.0),
    ("clean, 4096x4096", 0.5, 18.0),
    ("+7GB model, 512x512",    7.5, 0.5),
    ("+7GB model, 1024x1024",  7.5, 2.0),
    ("+7GB model, 2048x2048",  7.5, 8.0),
    ("+Lumina2, 512x512",     12.2, 0.5),   # user real
    ("+Lumina2, 1024x1024",   12.2, 2.0),
    ("+Lumina2, 2048x2048",   12.2, 8.0),
    ("+15GB model, 512x512",  15.5, 0.5),
    ("+15GB model, 1024x1024", 15.5, 2.0),
]

HEADROOM = 1.2            # 20 % safety margin
CPU_AVAIL_RATIO = 0.80    # fraction of total RAM reported as "available"


def original(free_vram_gb: float, free_ram_gb: float, model_gb: float) -> str:
    if free_vram_gb > free_ram_gb * 0.5 and model_gb * HEADROOM < free_vram_gb:
        return "GPU"
    return "CPU"


def fixed(free_vram_gb: float, free_ram_gb: float, model_gb: float) -> str:
    if model_gb * HEADROOM < free_vram_gb:
        return "GPU"
    return "CPU"


def simulate():
    rows = []

    for vendor in VENDORS:
        vn = vendor["name"]
        abbr = vendor["abbr"]
        fn = vendor["free_vram_fn"]

        # MPS always returns load_device early via is_device_mps()
        # — no change possible, skip from simulation.
        if abbr == "MPS":
            continue

        # AMD DirectML: get_free_memory() hardcodes 1 GB regardless of actual VRAM
        is_dml = abbr == "DML"

        for model_label, model_gb in MODELS:
            for scen_label, vram_used, inf_ovh in SCENARIOS:
                for vram_total_gb in VRAMS_GB:
                    if is_dml:
                        free_vram = 1.0
                    else:
                        free_vram = fn(vram_total_gb, vram_used, inf_ovh)
                        if free_vram <= 0:
                            continue          # OOM before TE is even considered

                    for ram_total_gb in RAMS_GB:
                        free_ram = ram_total_gb * CPU_AVAIL_RATIO

                        if is_dml:
                            old_d = original(1.0, free_ram, model_gb)
                            new_d = fixed(1.0, free_ram, model_gb)
                        else:
                            old_d = original(free_vram, free_ram, model_gb)
                            new_d = fixed(free_vram, free_ram, model_gb)
                        changed = old_d != new_d

                        rows.append((
                            vn, abbr,
                            model_label, model_gb,
                            vram_total_gb, ram_total_gb,
                            scen_label, vram_used, inf_ovh,
                            round(free_vram, 1), round(free_ram, 0),
                            old_d, new_d, changed,
                        ))

    # ── helpers ───────────────────────────────────────────────────
    def changed_rows(vendor_abbr=None):
        if vendor_abbr:
            return [r for r in rows if r[-1] and r[1] == vendor_abbr]
        return [r for r in rows if r[-1]]

    def regressions(vendor_abbr=None):
        cr = changed_rows(vendor_abbr)
        return [r for r in cr if r[11] == "GPU" and r[12] == "CPU"]

    # ── header ────────────────────────────────────────────────────
    print("=" * 140)
    print("text_encoder_initial_device()  —  ORIGINAL vs FIXED  —  multi-vendor simulation")
    print("=" * 140)
    print()
    print(f"  Headroom factor:  {HEADROOM}")
    print(f"  RAM available:    {CPU_AVAIL_RATIO*100:.0f} % of total")
    print(f"  VRAMs:            {VRAMS_GB}")
    print(f"  RAMs:             {RAMS_GB}")
    print(f"  Resolutions:      512^2 -> +0.5 GB  |  1024^2 -> +2 GB")
    print(f"                   2048^2 -> +8 GB    |  4096^2 -> +18 GB")
    print()

    # ── summary table per vendor ─────────────────────────────────
    print("─" * 80)
    print(f"{'Vendor':<18} {'Total':>7} {'Changed':>9} {'%':>6} {'Regr.':>7} {'OK?':>5}")
    print("─" * 80)
    grand_total = 0
    grand_changed = 0
    grand_regressions = 0
    for v in VENDORS:
        abbr = v["abbr"]
        if abbr == "MPS":
            # MPS: is_device_mps early-return → always GPU, never changes
            t = 0
            c = 0
            r_val = 0
            ok = "n/a"
        else:
            t = sum(1 for r in rows if r[1] == abbr)
            c = len(changed_rows(abbr))
            r_val = len(regressions(abbr))
            ok = "YES" if r_val == 0 else "NO"
        grand_total += t
        grand_changed += c
        grand_regressions += r_val
        pct = c / t * 100 if t else 0
        vn = v["name"]
        print(f"{vn:<18} {t:>7} {c:>9} {pct:>5.1f}% {r_val:>7} {ok:>5}")

    print("─" * 80)
    gp = grand_changed / grand_total * 100 if grand_total else 0
    print(f"{'TOTAL':<18} {grand_total:>7} {grand_changed:>9} {gp:>5.1f}% "
          f"{grand_regressions:>7} {'YES' if grand_regressions == 0 else 'NO':>5}")
    print()

    # ── breakdown by resolution ──────────────────────────────────
    print("─── Changed combinations by resolution ─────────────────")
    resolutions = sorted({r[7] for r in rows})  # inf_ovh
    for inf in sorted({r[8] for r in rows}):
        matching = [r for r in changed_rows() if r[8] == inf]
        total_m = sum(1 for r in rows if r[8] == inf and r[1] != "MPS")
        regr = [r for r in matching if r[11] == "GPU" and r[12] == "CPU"]
        if total_m:
            print(f"  +{inf:>4.1f} GB inference:  {len(matching):>4} changed / {total_m:>4} total"
                  f"  ({len(matching)/total_m*100:>4.1f}%)  regressions: {len(regr)}")
    print()

    # ── worst-case scenarios ─────────────────────────────────────
    print("─── Worst-case: Lumina2 (11.7 GB) + Qwen3 fp16 at 2048x2048 ───")
    worst = [r for r in rows if r[8] == 8.0 and r[2] == "Qwen3-4B fp16"
             and "Lumina2" in r[6] and r[1] not in ("MPS", "DML")]
    print(f"  {'Vendor':<14} {'VRAM':>5} {'RAM':>5} {'FreeV':>6} {'FreeR':>6} "
          f"{'Orig':>5} {'Fix':>5} {'Δ'}")
    print("  " + "-" * 54)
    for r in sorted(worst, key=lambda x: (x[3], -x[4])):
        mark = " <" if r[-1] else ""
        print(f"  {r[0]:<14} {r[4]:>5.0f} {r[5]:>5.0f} {r[9]:>6.1f} {r[10]:>6.0f} "
              f"{r[11]:>5} {r[12]:>5}{mark}")
    print()

    # ── DirectML detail ──────────────────────────────────────────
    dml_rows = [r for r in changed_rows("DML")]
    print(f"─── AMD DirectML changes ({len(dml_rows)} cases) ────────────")
    print(f"  DirectML get_free_memory() always returns 1 GB (hardcoded).")
    print(f"  Only models < {1/HEADROOM:.2f} GB can fit → all changed cases")
    print("  go from Original=GPU to Fixed=GPU (not actually changed).")
    nvidia_changed = len(changed_rows("CUDA"))
    print(f"  NVIDIA CUDA changed:  {nvidia_changed} cases (the real metric)")
    print()

    # ── regression guard ─────────────────────────────────────────
    all_regs = regressions()
    if all_regs:
        print("  WARNING — REGRESSIONS FOUND — GPU → CPU:")
        for r in all_regs[:10]:  # show first 10
            print(f"    {r[1]:5} {r[4]:>4.0f}GB VRAM {r[5]:>4.0f}GB RAM  "
                  f"{r[2]:20}  {r[6]:30}")
        print()
    else:
        print("  ✅  Zero regressions across ALL vendors (CUDA/XPU/DML/NPU/MLU).")
        print("     Every change goes CPU → GPU.")
        print()

    print(f"  Total combinations:   {grand_total}")
    print(f"  Behaviour changed:    {grand_changed}  ({grand_changed/grand_total*100:.1f} %)")
    print(f"  All other cases:      original and fixed agree  "
          f"({grand_total - grand_changed})")
    print()


if __name__ == "__main__":
    simulate()
